export const data = {
  title: "Inginer Software",
  employer: "Bombardier SRL",
  departament: "It hardware / software",
  location: "Cluj-Napoca, Cluj, Romania",
  workingHours: "Cu norma intreaga / Partiala",
  jobType: "Telemunca / La birou / Hibrid",
  experience: "Experienta 0-3 ani / Internship / Practica",
  postedAt: "22 Martie 2023",
  salary: "3000 -  8000 Lei",
  jobDescription:
    "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing.",
  responsabilities: [
    "Automate build and deployment processes for cloud hosting environments",
    "Develop code and configure tools for provisioning various IaaS, PaaS, SaaS cloud resources",
    "Handle lifecycle management of certificates & secrets",
    "Work closely with developer teams to create automated CI/CD pipelines",
    "Manage infrastructure & setup (new application instances, domain management, backups)",
    "Maintenance of the internal systems and Continuous Integration tools(monitoring, Jenkins, Nexus, Sonar)",
    "Contribute to the infrastructure architecture of different systems on the AWS and/or Azure",
    "Implement monitoring and alerting (CloudWatch alarms, health checks, ELK alerts)",
    "Database maintenance (PostgreSQL, MongoDB)",
    "Assist with organisation-wide security aspects",
  ],
  demands: [
    "Minimum 3 years of experience with a strong background in Linux and AWS and/or Azure",
    "Hands-on experience with DevOps tools like Terraform, Ansible, Jenkins",
    "Experience with monitoring and reporting tools like Elasticsearch, Kibana",
    "Experience with administration of DB servers: PostgreSQL, MongoDB",
    "Ability and desire to code in Python, Go and Linux Bash",
    "Good knowledge of networking & security",
    "Good knowledge of Git",
    "Nice to have: experience with Kubernetes, IAM services (like Okta) and products (like Keycloak)",
  ],
  oferings: [
    "Exciting projects most of the time with direct customer contact",
    "Experienced team members with high professional standards",
    "Dedicated technical coaching from a more experienced colleague",
    "Internal and external trainings, certification programs and a learning path",
    "Hybrid working style: what best suits you, the team and the project",
    "Competitive salary and benefits package",
    "Sport activities like biking, tennis, football, hiking etc.",
  ],
  generalInfo: [
    "Durata: nederminata",
    "Tipul de job: norma intreaga",
    "Experienta: senior, 4+ ani",
    "Locatia: 100% Remote",
  ],
  aboutEmployer: {
    photo: "linktophoto.com",
    name: "Laura Lavrici",
    title: "Recruter",
    phone: "0766 555 444",
    fax: "0766 555 444",
    email: "emailultau@yahoo.com",
    address: "Apahida, Strada pacii, nr 123",
  },
};
